const translations = {
    pt: {
        "nav-home": "início",
        "nav-sobre": "sobre",
        "nav-habilidades": "habilidades",
        "nav-projetos": "projetos",
        "nav-certificacoes": "certificações",
        "nav-contato": "contato",
        "principal-description": "Desenvolvedor Full Stack com foco em soluções escaláveis, combinando visão estratégica, código limpo e entrega de valor.",
        "principal-ver-trabalhos": "Ver trabalhos",
        "principal-baixar": "Baixar CV",
        "about-description-one": "Me chamo Felipe, sou um desenvolvedor Full Stack em constante evolução, apaixonado por criar aplicações modernas, performáticas e com foco em experiência do usuário.",
        "about-description-two": "Tenho conhecimento em tecnologias como HTML, CSS, JavaScript, Tailwind CSS, Bootstrap, Python e Java, com aprendizado contínuo em frameworks e boas práticas de desenvolvimento.",
        "about-description-three": "Busco sempre escrever código limpo, escalável e com atenção aos detalhes de design e usabilidade.",
        "habilidades-tittle": "Habilidades",
        "habilidades-more-details": "Mais detalhes",
        "projetos-tittle": "Meus Projetos",
        "projetos-tittle-cadastro-project": "Cadastro de Usuário",
        "projetos-tittle-analysis-project": "Análise de Vendas",
        "projetos-description-one": "EconoMy é um software desenvolvido em Java, projetado para simular uma conta bancária. Seu principal objetivo é oferecer ao usuário uma experiência segura e prática para realizar transferências e receber valores, funcionando como uma ferramenta de apoio financeiro.",
        "projetos-description-two": "Fyvo é uma fintech brasileira criada com o objetivo de ajudar as pessoas a organizar, acompanhar e melhorar o controle das suas finanças pessoais. Através de ferramentas simples e intuitivas, o projeto oferece apoio na administração de gastos, planejamento financeiro e construção de hábitos mais saudáveis com o dinheiro.",
        "projetos-description-three": "Este projeto é um sistema simples de cadastro de usuários, desenvolvido em Python puro. A persistência dos dados é feita utilizando o módulo JSON, garantindo o armazenamento e recuperação das informações de forma prática e eficiente.",
        "projetos-description-four": "Projeto de análise de dados de vendas utilizando SQL para consultas e extração de insights. Focado em gerar relatórios e métricas que ajudam a entender o desempenho comercial e apoiar a tomada de decisões.",
        "contact-tittle": "Contato",
        "contact-description": "Interessado(a) em trabalhar juntos? Entre em contato para discutirmos seu próximo projeto.",
        "contact-linkedin-button": "Contato via Linkedin",
        "footer-description": "© 2025 devfenrir todos os direitos reservados."
    },
    en: {
        "nav-home": "home",
        "nav-sobre": "about",
        "nav-habilidades": "skills",
        "nav-projetos": "projects",
        "nav-certificacoes": "certifications",
        "nav-contato": "contact",
        "principal-description": "Full Stack Developer focused on scalable solutions, combining strategic vision, clean code, and value delivery.",
        "principal-ver-trabalhos": "View works",
        "principal-baixar": "Download CV",
        "about-description-one": "My name is Felipe, I'm a constantly evolving Full Stack developer, passionate about creating modern, high-performance applications focused on user experience.",
        "about-description-two": "I have knowledge in technologies like HTML, CSS, JavaScript, Tailwind CSS, Bootstrap, Python, and Java, with continuous learning in frameworks and best development practices.",
        "about-description-three": "I always strive to write clean, scalable code with attention to design details and usability.",
        "habilidades-tittle": "Skills",
        "habilidades-more-details": "More details",
        "projetos-tittle": "My Projects",
        "projetos-tittle-cadastro-project": "User Registration",
        "projetos-tittle-analysis-project": "Sales Analysis",
        "projetos-description-one": "EconoMy is a Java-based software designed to simulate a bank account. Its main goal is to offer users a secure and practical experience for making transfers and receiving funds, serving as a financial support tool.",
        "projetos-description-two": "Fyvo is a Brazilian fintech created to help people organize, monitor, and improve control over their personal finances. Through simple and intuitive tools, the project supports expense management, financial planning, and the development of healthier money habits.",
        "projetos-description-three": "This project is a simple user registration system developed in pure Python. Data persistence is handled using the JSON module, ensuring practical and efficient information storage and retrieval.",
        "projetos-description-four": "Sales data analysis project using SQL for queries and insights extraction. Focused on generating reports and metrics that help understand business performance and support decision-making.",
        "contact-tittle": "Contact",
        "contact-description": "Interested in working together? Get in touch so we can discuss your next project.",
        "contact-linkedin-button": "Contact via LinkedIn",
        "footer-description": "© 2025 devfenrir all rights reserved."
    },
    es: {
        "nav-home": "inicio",
        "nav-sobre": "sobre",
        "nav-habilidades": "habilidades",
        "nav-projetos": "proyectos",
        "nav-certificacoes": "certificaciones",
        "nav-contato": "contacto",
        "principal-description": "Desarrollador Full Stack enfocado en soluciones escalables, combinando visión estratégica, código limpio y entrega de valor.",
        "principal-ver-trabalhos": "Ver trabajos",
        "principal-baixar": "Descargar CV",
        "about-description-one": "Me llamo Felipe, soy un desarrollador Full Stack en constante evolución, apasionado por crear aplicaciones modernas, de alto rendimiento y con enfoque en la experiencia del usuario.",
        "about-description-two": "Tengo conocimientos en tecnologías como HTML, CSS, JavaScript, Tailwind CSS, Bootstrap, Python y Java, con aprendizaje continuo en frameworks y buenas prácticas de desarrollo.",
        "about-description-three": "Siempre busco escribir código limpio, escalable y con atención a los detalles de diseño y usabilidad.",
        "habilidades-tittle": "Habilidades",
        "habilidades-more-details": "Más detalles",
        "projetos-tittle": "Mis Proyectos",
        "projetos-tittle-cadastro-project": "Registro de Usuario",
        "projetos-tittle-analysis-project": "Análisis de Ventas",
        "projetos-description-one": "EconoMy es un software desarrollado en Java, diseñado para simular una cuenta bancaria. Su principal objetivo es ofrecer al usuario una experiencia segura y práctica para realizar transferencias y recibir valores, funcionando como una herramienta de apoyo financiero.",
        "projetos-description-two": "Fyvo es una fintech brasileña creada para ayudar a las personas a organizar, seguir y mejorar el control de sus finanzas personales. A través de herramientas simples e intuitivas, el proyecto ofrece apoyo en la gestión de gastos, planificación financiera y construcción de hábitos más saludables con el dinero.",
        "projetos-description-three": "Este proyecto es un sistema simple de registro de usuarios, desarrollado en Python puro. La persistencia de datos se realiza utilizando el módulo JSON, garantizando el almacenamiento y recuperación de la información de forma práctica y eficiente.",
        "projetos-description-four": "Proyecto de análisis de datos de ventas utilizando SQL para consultas y extracción de insights. Enfocado en generar informes y métricas que ayuden a entender el rendimiento comercial y apoyar la toma de decisiones.",
        "contact-tittle": "Contacto",
        "contact-description": "¿Interesado(a) en trabajar juntos? Ponte en contacto para que podamos hablar sobre tu próximo proyecto.",
        "contact-linkedin-button": "Contacto por LinkedIn",
        "footer-description": "© 2025 devfenrir todos los derechos reservados."
    }
};